# Generated by Django 4.2.3 on 2023-08-23 14:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0003_remove_registration_currentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='currentdate',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
