# Generated by Django 4.2.3 on 2023-08-23 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0004_registration_currentdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='currentdate',
        ),
    ]
