# Generated by Django 4.2.3 on 2023-08-23 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration', '0005_remove_registration_currentdate'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='registration_d',
            field=models.CharField(default='Null', max_length=200),
        ),
    ]
