# Generated by Django 4.2.3 on 2023-08-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Office',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('subject', models.CharField(max_length=200)),
                ('contact', models.CharField(max_length=20)),
                ('message', models.TextField()),
            ],
        ),
    ]
